In [1]:
import pandas as pd
import time

In [2]:
import webbrowser
import requests

In [3]:
import numpy as np
from bs4 import BeautifulSoup

In [4]:
import urllib.parse
import urllib.request
import ssl

In [5]:
df = pd.read_excel("elTab.xlsx")
df.head()

               Venue Name    Location
0              Dear Grace         NaN
1            ABQ Funhouse     Hackney
2  The Bletchley Funhouse     Chelsea
3     H Division Funhouse  Shoreditch
4                Bar Elba    Waterloo

In [17]:
addresses = []
bar_address_dict = {}

for index,row in df.iterrows():
    
    bar_name = row[0].replace(' ', '+')
    location_name = str(row[1]).replace(' ','+')

    if pd.isnull(row[1]) == True:
        search_term = bar_name +'+'+ 'London+Address'
    else:
        search_term = bar_name +'+'+ location_name +'+'+ 'London+Address'
    
    url = f"https://www.google.com.tr/search?q={search_term}"
    
    print('Searching address for: ', bar_name)
    
    try:
        # Get Google page + parse
        r = requests.get(url)
        soup = BeautifulSoup(r.text, 'html.parser')

        with requests.Session() as s:
            
            headers = {
                "referer":"referer: https://www.google.com/",
                "user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
                }
            s.post(url, headers=headers)
            response = s.get(url, headers=headers)
            soup = BeautifulSoup(response.text, 'html.parser')
            result = soup.find_all("div", {"class": "sXLaOe"})
            
            if result == []:
                print('no address found')
            for res in result:
                address = res.decode_contents().strip()
                addresses.append(address)
                print('Address found for ', row[0], ' is ', address )
                bar_address_dict[row[0]] = address
    except:
        print("Failed searching for address of:", bar_name)
        addresses.append('')
        bar_address_dict[row[0]] = ''
    time.sleep(5)

Searching address for:  Dear+Grace
Address found for  Dear Grace  is  195 Wood Ln, London W12 7FQ
Searching address for:  ABQ+Funhouse
no address found
Searching address for:  The+Bletchley+Funhouse
Address found for  The Bletchley Funhouse  is  459 King's Rd, London SW10 0LJ
Searching address for:  H+Division+Funhouse
no address found
Searching address for:  Bar+Elba
Address found for  Bar Elba  is  Rooftop Mercury House, 109-117 Waterloo Rd, London SE1 8UL
Searching address for:  The+Cocktail+Club
no address found
Searching address for:  Percy's
Address found for  Percy's  is  2a Kensington High St, London W8 4PT
Searching address for:  People's+Park+Tavern
Address found for  People's Park Tavern  is  360 Victoria Park Rd, London E9 7BT
Searching address for:  Barrio+Bars
no address found
Searching address for:  The+Owl+and+Hitchhiker
Address found for  The Owl and Hitchhiker  is  471 Holloway Rd, Archway, London N7 6LE
Searching address for:  The+Four+Thieves
Address found for  The Four Thieves  is  51 Lavender Gardens, London SW11 1DJ
Searching address for:  The+Gunmakers
Address found for  The Gunmakers  is  13 Eyre St Hill, London EC1R 5ET
Searching address for:  El+Ta'Koy
Address found for  El Ta'Koy  is  3 Henrietta St, London WC2E 8LU
Searching address for:  Tequila+Mockingbird
no address found
Searching address for:  Jujus+Bar+and+Stage
Address found for  Jujus Bar and Stage  is  Ely's Yard, 15 Hanbury St, London E1 6QR
Searching address for:  Tonight+Josephine
no address found
Searching address for:  Callooh+Callay
Address found for  Callooh Callay  is  65 Rivington St, London EC2A 3AY
Searching address for:  London+Cocktail+Club
no address found
Searching address for:  Blame+Gloria
Address found for  Blame Gloria  is  20 Bedford St, London WC2E 9HP
Searching address for:  93+Feet+East
Address found for  93 Feet East  is  150 Brick Ln, London E1 6QL
Searching address for:  Ninety+One+Living+Room
Address found for  Ninety One Living Room  is  91 Brick Ln, London E1 6QL
Searching address for:  Near+and+Far
no address found
Searching address for:  Battersea+barge
Address found for  Battersea barge  is  Nine Elms Ln, Nine Elms, London SW11 8PZ
Searching address for:  Little+Bat
Address found for  Little Bat  is  54 Islington Park St, London N1 1PX
Searching address for:  Boom+Battle+Bar
no address found
Searching address for:  Isla+Ray
Address found for  Isla Ray  is  37 Deptford High St, London SE8 4AD
Searching address for:  Little+Nans
Address found for  Little Nans  is  London SE8 4BZ
Searching address for:  Peachy+Queen+Bar
Address found for  Peachy Queen Bar  is  12 Putney High St, London SW15 1SL
Searching address for:  The+Duchess+of+Dalston
no address found
Searching address for:  Cherry+Galore
Address found for  Cherry Galore  is  Basement, 129 Stoke Newington High St, London N16 0PH
Searching address for:  Kraft+Dalston
Address found for  Kraft Dalston  is  Kraft Dalston Bar &amp; Restaurant inside Kingsland Locke, 130a Kingsland High St, London E8 2LQ
Searching address for:  No+Boring+Beer
no address found